### ISSUE TITLE
install error using latelst kali

### ISSUE THREAD

**Issue by dan7ez** [0x776b7364/misc-scripts#1]
in the browser i get this error - saying "Web application could not be started - phusion passenger has listed more info about this error below

cannot load such file -- bundler/setup (LoadError)
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in require' /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:inrequire'
/usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:430:in activate_gem' /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:297:inblock in run_load_path_setup_code'
/usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:435:in running_bundler' /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:296:inrun_load_path_setup_code'
/usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:100:in preload_app' /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:156:inmodule:App'
/usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:30:in module:PhusionPassenger' /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:29:in
'

Error ID
91d88707
Application root
/var/www/phishing-frenzy

**Comment by 0x776b7364** [comment]
Are you using 2016.2, or a weekly build?

**Comment by dan7ez** [comment]
Hi, 

thanks for your quick reply!

i download torrent iso of 2016.2 64 bit and then did a apt-get dist-upgrade (thats what i currently have setup - kali running in VMware fusion on my mac)

not sure if that answers your question?

I am keen to get phishing frenzy up and running... i have been unsuccessful with getting it up and running on both ubuntu and kali now... the latest version of kali is the main thing I use so would prefer to get it up and running on that... however... i also have ubuntu backbox installed if necessary...

Are you able to either update your frenzy install script or give me or tell me where i can get a copy of frenzy thats already installed and setup on an precompiled image etc?

Many Thanks,
Dan7ez

**Comment by 0x776b7364** [comment]
Check out 89d9023 and let me know if you still have errors.

**Comment by dan7ez** [comment]
Hi,

Wonderful! works perfect!

Look forward to testing out frenzy etc... 

Thank you very much for putting together the script and updating it so quickly!

Cheers,
Dan7ez

**Comment by 0x776b7364** [comment]
You're welcome. :)
